# -*- MakeFile -*-
# unit test for dmalloc wrappers
#

sources := dmalloc.cpp dmalloc_stat.cpp dmalloc_log.cpp
uname := $(shell uname -s)
ifeq ($(uname), Linux)
	os = LINUX
	sources += libc_wrapper_linux.cpp
endif
ifeq ($(uname), Darwin)
	os = DARWIN
endif
objects := $(sources:.cpp=.o)
depends := $(objects:.o=.d)

target := unit_test_dmalloc

%.o:%.cpp
	g++ -std=c++17 -g -D DMALLOC_DEBUG  -D DMALLOC_UNIT_TEST_DMALLOC -D $(os) -Wall -Wextra -Werror -c $< -o $@
	@gcc -MM $*.cpp > $*.d

$(target):$(objects)
	g++ -g $^ -o $@

clean:
	rm -f *.o *.d *~ $(target)

-include $(depends)

